name: Check

on: [push, pull_request]

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        py-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Set up Python ${{ matrix.py-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py-version }}

      - uses: actions/checkout@v2

      - name: Perform checks
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          flake8 pika-stubs
          mypy -p pika-stubs --strict
